/** Importing this file creates the necessary side effects to allow using any web component used in this project */

import './components/category-adder';
import './components/add-item';
import './components/audio-control';
import './components/audio-player';
import './components/item-editor';
import './components/playable-track';
import './components/progress-indicator';
import './components/confirm-dialog';
import './components/dialog-button';
import './components/dismiss-dialog';
import './components/titled-item';
import './components/track-data';
import './components/validated-adder';
import './components/wave-details';
import '@vaadin/vaadin-checkbox/theme/material/vaadin-checkbox';
import '@vaadin/vaadin-text-field/theme/material/vaadin-text-field';
import '@vaadin/vaadin-accordion/theme/material/vaadin-accordion';
import '@vaadin/vaadin-accordion/theme/material/vaadin-accordion-panel';
import '@vaadin/vaadin-button/theme/material/vaadin-button';
import '@vaadin/vaadin-details/theme/material/vaadin-details';
import '@vaadin/vaadin-dialog/theme/material/vaadin-dialog';
import '@vaadin/vaadin-icons/vaadin-icons';
import '@vaadin/vaadin-item/theme/material/vaadin-item';
import '@vaadin/vaadin-tabs/theme/material/vaadin-tabs';
import '@vaadin/vaadin-tabs/theme/material/vaadin-tab';
import '@vaadin/vaadin-ordered-layout/theme/material/vaadin-vertical-layout';
import '@vaadin/vaadin-progress-bar/theme/material/vaadin-progress-bar';